# Generated by Django 5.2 on 2025-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_category_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('ML', 'Milk'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('CR', 'Curd'), ('PN', 'Paneer'), ('CZ', 'Cheese'), ('IC', 'Ice-cream'), ('CH', 'Chocolate'), ('MS', 'Milkshake'), ('MB', 'Mobile'), ('TV', 'TV'), ('LP', 'Laptop'), ('FR', 'Fruits'), ('VG', 'Vegetables'), ('GRI', 'Grains'), ('SP', 'Spices'), ('WTP', 'Tops'), ('WSR', 'Sarees'), ('WDR', 'Dresses'), ('WJE', 'Jeans'), ('WST', 'Skirts'), ('MSH', 'Shirts'), ('MTS', 'T-Shirts'), ('MJE', 'Jeans'), ('MTR', 'Trousers'), ('MSL', "Men's Slippers"), ('MSH', "Men's Shoes"), ('WSH', "Women's Heels"), ('WSN', "Women's Sneakers"), ('FIC', 'Fiction'), ('NFC', 'Non-fiction'), ('EDU', 'Educational'), ('COM', 'Comics'), ('BIO', 'Biographies')], default='ML', max_length=4),
        ),
    ]
